import { type WeierstrassPoint } from '@noble/curves/abstract/weierstrass.js';

import { Amount, type AmountLike } from './Amount';
import { type SerializedBlindedMessage } from './types/index';

class BlindedMessage {
  // NUT #00: `amount` is the value for the requested `BlindSignature`, `id` is the requested keyset ID from which we expect a signature, and `B_` is the blinded secret message generated by `Alice`.
  private readonly amountValue: Amount;
  B_: WeierstrassPoint<bigint>;
  id: string;
  constructor(amount: AmountLike, B_: WeierstrassPoint<bigint>, id: string) {
    this.amountValue = Amount.from(amount);
    this.B_ = B_;
    this.id = id;
  }

  get amount(): Amount {
    return this.amountValue;
  }

  getSerializedBlindedMessage(): SerializedBlindedMessage {
    // NUT #00: When a curve point is serialised as `hex_str`, it is the hex encoding of the SEC1 compressed public key bytes, unless a NUT specifies a different encoding.
    return { amount: this.amountValue, B_: this.B_.toHex(true), id: this.id };
  }
}
export { BlindedMessage };
