import { type Amount, type AmountLike } from '../Amount';

import { type SerializedDLEQ } from './blinded';

/**
 * A proof-shaped object whose `amount` field has not yet been normalized to `Amount`.
 *
 * Use this type to model proofs coming from external storage (localStorage, databases, JSON blobs)
 * where `amount` may be a `number`, `string`, or any other {@link AmountLike} value.
 *
 * @see {@link Proof} for the fully normalized type with `amount: Amount`.
 */
export type ProofLike = Omit<Proof, 'amount'> & { amount: AmountLike };

// NUT #00: A `Proof` is also called an _input_ and is generated by `Alice` from a `BlindSignature` it received. An array `[Proof]` is called `Proofs`. `Alice` sends `Proofs` to `Bob` for [melting tokens][05]. [Serialized](#serialization-of-tokens) `Proofs` can also be sent from `Alice` to `Carol`. Upon receiving the token, `Carol` deserializes it and requests a [swap][03] from `Bob` to receive new `Proofs`.
// NUT #00: `amount` is the amount of the `Proof`, `secret` is the secret message and is a utf-8 encoded string (the use of a 64 character hex string generated from 32 random bytes is recommended to prevent fingerprinting), `C` is the unblinded signature on `secret` (hex string), `id` is the [keyset id][02] of the mint public keys that signed the token (hex string).

/**
 * Represents a single Cashu proof.
 */
export type Proof = {
  /**
   * Keyset id, used to link proofs to a mint and its MintKeys.
   */
  id: string;
  /**
   * Amount denominated in unit of the mints keyset id.
   */
  amount: Amount;
  /**
   * The initial secret that was (randomly) chosen for the creation of this proof.
   */
  secret: string;
  /**
   * The unblinded signature for this secret, signed by the mints private key.
   */
  C: string;
  /**
   * DLEQ proof.
   */
  dleq?: SerializedDLEQ;
  /**
   * The P2BK ephemeral pubkey "E" (SEC1-compressed 33-byte hex).
   */
  p2pk_e?: string;
  /**
   * The witness for this proof.
   */
  witness?: string | P2PKWitness | HTLCWitness;
};

/**
 * P2PK witness.
 */
export type P2PKWitness = {
  /**
   * An array of signatures in hex format.
   */
  signatures?: string[];
};

/**
 * HTLC witness.
 */
export type HTLCWitness = {
  /**
   * Preimage.
   */
  preimage: string;
  /**
   * An array of signatures in hex format.
   */
  signatures?: string[];
};
